title: Brennan's Cybersecurity Lab
description: Purple Team Testing Environment & Security Research
url: "https://brennancybersec.github.io"

markdown: kramdown

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
